apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kafka-adapter-deploy
  labels:
    app: kafka-adapter
spec:
  replicas: 4
  selector:
    matchLabels:
      app: kafka-adapter
  template:
    metadata:
      labels:
        app: kafka-adapter
    spec:
      volumes:
        -
          configMap:
            items:
              - key: config.yaml
                path: config.yaml
            name: kafka-adapter-config
          name: kafka-adapter-config-volume
      containers:
      - name: kafka-adapter
        image: yuriadams/prometheus-kafka-adapter:stable
        resources:
          limits:
            cpu: "1"
            memory: "1.5Gi"
          requests:
            cpu: 100m
            memory: "1.5Gi"
        env:
         - name: CONFIG_PATH
           valueFrom:
             configMapKeyRef:
               name: kafka-adapter-config
               key: config.path
        ports:
        - containerPort: 9201
        volumeMounts:
          -
            mountPath: /go/src/app/app-config
            name: kafka-adapter-config-volume
