apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: elasticsearch-adapter-deploy
  labels:
    app: elasticsearch-adapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch-adapter
  template:
    metadata:
      labels:
        app: elasticsearch-adapter
    spec:
      volumes:
        -
          configMap:
            items:
              - key: config.yaml
                path: config.yaml
            name: elasticsearch-adapter-config
          name: elasticsearch-adapter-config-volume
      containers:
      - name: elasticsearch-adapter
        image: yuriadams/prometheus-elasticsearch-adapter:latest
        env:
         - name: AWS_ACCESS_KEY
           valueFrom:
             configMapKeyRef:
               name: elasticsearch-adapter-config
               key: aws.access
         - name: AWS_SECRET_KEY
           valueFrom:
             configMapKeyRef:
               name: elasticsearch-adapter-config
               key: aws.secret
         - name: CONFIG_PATH
           valueFrom:
             configMapKeyRef:
               name: elasticsearch-adapter-config
               key: config.path      
        ports:
        - containerPort: 9201
        volumeMounts:
          -
            mountPath: /go/src/app/app-config
            name: elasticsearch-adapter-config-volume
