kind: Service
apiVersion: v1
metadata:
  name: kafka-adapter-service
  labels:
    k8s-app: kafka-adapter
spec:
  selector:
    app: kafka-adapter
  ports:
   - name: web
     protocol: TCP
     port: 9201
     targetPort: 9201
  type: LoadBalancer
